{{- if eq .Values.main.embedding.name "gte-1.5" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-orca
  namespace: {{ .Release.Namespace }}
  labels:
    tag: {{ .Chart.Version }}-{{ .Release.Name }}
    {{- with .Values.labels.orca }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      tag: {{ .Chart.Version }}-{{ .Release.Name }}
      {{- with .Values.labels.orca }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        tag: {{ .Chart.Version }}-{{ .Release.Name }}
        {{- with .Values.labels.orca }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      volumes:
      - name: tmp
        emptyDir: {}
      - name: app-profiles
        configMap:
          name: app-profile-cm        
      containers:
      - name: orca-ctr
        image: {{ .Values.images.orca.image }}:{{ .Values.images.orca.tag }}
        imagePullPolicy: {{ .Values.images.orca.pullPolicy }}
        ports:
        - containerPort: {{ (index .Values.services.orca.ports 0).targetPort }}
          name: orca-http
        env:
        - name: QDRANT_HOST
          value: "qdrant-service.hawk.svc.cluster.local:6334"
        - name: VLLM_HOST
          value: {{ .Release.Name }}-{{ .Values.services.vllm.name }}
        - name: EMBED_SERVICE_TYPE
          value: "gte-qwen:{{ .Release.Name }}-{{ .Values.services.embedding.name }}"
        - name: QWEN_MODEL_NAME
          value: {{ index .Values.main.vllm.inference_model | default "Qwen/Qwen2.5-7B-Instruct" | quote }}
        - name: FIBER_PORT
          value: {{ (index .Values.services.orca.ports 0).targetPort | quote}}
        - name: TRANSFORMERS_OFFLINE
          value: "1"
        - name: CODE_COLLECTION
          value: "gte-code_chunks"
        - name: CHANGE_COLLECTION
          value: "gte-change_chunks"
        - name: DOC_COLLECTION
          value: "gte-doc_chunks"
        - name: GEN_DOC_COLLECTION
          value: "gte-gen_doc_chunks"
        - name: FIBER_READ_TIMEOUT
          value: "180s"
        - name: FIBER_WRITE_TIMEOUT
          value: "280s"
        - name: FIBER_IDLE_TIMEOUT
          value: "180s"
        - name: VLLM_TIMEOUT
          value: "380s"
        - name: EMBED_TIMEOUT
          value: "120s"
        - name: APP_PROFILE_DIR
          value: "/etc/app-prof"
      {{ with .Values.main }}
        {{- if .embedding.re_rank }}  
        - name: RERANK_ENABLED
          value: {{ .embedding.re_rank | quote }}
        - name: RERANK_OVERFETCH_MULTIPLIER
          value: {{ .embedding.re_rank_overfetch | quote }}       
        {{- end }}
        - name: QDRANT_SCORE_THRESHOLD
          value: {{ .orca.score_threshold | quote | default "0" }}
        - name: QDRANT_MMR_ENABLED
          value: {{ .orca.mmr | quote }}
        - name: QDRANT_MMR_LAMBDA
          value: {{ .orca.mmr_lambda | quote }}
        - name: QDRANT_MMR_OVERFETCH
          value: {{ .orca.mmr_overfetch | quote }}     
        - name: CONTEXT_TRUNCATION_ENABLED
          value: {{ .orca.context_truncation | quote }}
      {{- end }}  
        volumeMounts:
        - name: app-profiles
          mountPath: /etc/app-prof
          readOnly: true        
        - name: tmp
          mountPath: /tmp
        {{ with .Values.resources.orca }}
        resources:
          {{ toYaml . | nindent 10 }}
        {{ end }}
{{ end }}