apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orca-prod
  namespace: argocd
spec:
  destination:
    namespace: hawk
    server: kubernetes.default
  source:
    path: .
    repoURL: https://github.com/ImMnan/helm-rag_vLLM.git
    targetRevision: HEAD
    helm:
      releaseName: prod
      valueFiles:
        - Argo/orca-production-values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
