
# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
main: 
  embedding: 
    name: gte-1.5 #e5-large

  vllm: 
    inference_model: Qwen/Qwen2.5-7B-Instruct
    runCmd: |-
      vllm serve Qwen/Qwen2.5-7B-Instruct
      --gpu-memory-utilization 0.90
      --port 8000
      --tensor-parallel-size 1
      --enable-prefix-caching
    
  vectorDB: qdrant #default: qdrant
  
images:
  orca: 
    image: immnan/rag-go
    pullPolicy: IfNotPresent
    tag: "0.8.9"
  embedding: 
    image: immnan/gte-embed-py
    pullPolicy: IfNotPresent
    tag: "0.1.0"
  mini_ui: 
    image: immnan/mini-ui
    pullPolicy: IfNotPresent
    tag: "0.1.9"
  vllm:
    image: vllm/vllm-openai
    pullPolicy: IfNotPresent
    tag: "latest"
# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: 
    iam.gke.io/gcp-service-account: support-sales@appspot.gserviceaccount.com
  labels: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: "rag-gateway-ksa"

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: 
  orca: {}
  embedding: {}
  ui: {}

# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
labels: 
  
  vllm: 
    app: qwen-2.5
    type: vllm

  orca: 
    app: orca
    type: rag-go
  
  mini_ui: 
    app: mini-ui
    type: ui    

  embedding:
    app: gte-embed 
    type: embedding-model    



podSecurityContext:
  orca: {}
  embedding: {}
  vllm: {}

securityContext: 
  orca: {}
  embedding: {}
  vllm: {}

resources: 
  orca: 
    requests:
      cpu: "500m"
      memory: 2Gi
    limits:
      cpu: "1"
      memory: 4Gi
  embedding: 
    requests:
      cpu: "500m"
      memory: 4Gi
    limits:
      cpu: "1"
      memory: 8Gi  
  vllm: 
    requests:
      cpu: "1"
      memory: "8Gi"
      nvidia.com/gpu: "1"  
    limits:
      cpu: "2"
      memory: "16Gi"
      nvidia.com/gpu: "1"
  mini_ui: 
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "4Gi"

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling: 
  orca: {}

nodeSelector: 
  orca: {}
  embedding: {}
  ui: {}

tolerations: 
  orca: []
  embedding: []
  vllm:
  - key: "nvidia.com/gpu"
    operator: "Exists"
    effect: "NoSchedule"  

affinity: 
  orca: []
  embedding: {}
  ui: {}

services:
  vllm: 
    name: qwen-svc
    type: ClusterIP
    ports: 
    - port: 80
      targetPort: 8000
      name: llm-http

  orca: 
    name: orca-svc
    type: ClusterIP
    ports: 
    - port: 80
      targetPort: 8080
      name: http

  embedding: 
    name: embed-gte-svc
    type: ClusterIP
    ports: 
    - port: 80
      protocol: TCP
      targetPort: 8000
      name: embed-http

  mini_ui: 
    name: mini-ui-svc
    type: ClusterIP
    ports: 
    - port: 80
      targetPort: 3000
      name: http
