apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: hawk
  name: rag-gateway-ksa
  annotations:
    iam.gke.io/gcp-service-account: support-sales@appspot.gserviceaccount.com
automountServiceAccountToken: true
